name: CI

on:
  pull_request:

# Automatically cancel any previous runs of this workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-check-snowflake:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER_CI: ${{ secrets.SNOWFLAKE_CI_USER }}
      SNOWFLAKE_PASSWORD_CI: ${{ secrets.SNOWFLAKE_CI_USER_PASSWORD }}
      SNOWFLAKE_DATABASE_CI: DBT_PACKAGE_CI
      SNOWFLAKE_ROLE_CI: PACKAGE_CI_ROLE
      SNOWFLAKE_WAREHOUSE_CI: PACKAGE_CI_WH
    steps:
      - name: Checkout branch
        id: checkout-branch
        uses: actions/checkout@v3

      - name: Set schema name
        id: set-schema-name
        run: |
          if [ "${{ github.actor }}" = "dependabot[bot]" ]; then
            echo "schema_name=dependabot" >> $GITHUB_OUTPUT
          else
            echo "schema_name=${{ github.actor }}" >> $GITHUB_OUTPUT
          fi

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with: { enable-cache: true }

      - name: Install dependencies
        run: uv sync --no-default-groups --group dbt

      - name: Run integration tests
        env:
          SNOWFLAKE_SCHEMA_CI: DBT_CI_${{github.event.number}}_${{ steps.set-schema-name.outputs.schema_name }}
        run: |
          uv run ./run_test.sh
